sylius_mailer:
    emails:
        !php/const App\Mailer\Emails::BRAND_APPROVAL:
            template: 'email/brand_approval.html.twig'
        !php/const App\Mailer\Emails::ORDER_CONFIRMATION:
            enabled: false
