sylius_grid:
    templates:
        action:
            show_products: 'admin/grid/action/show_products.html.twig'
        filter:
            update_delay: 'admin/grid/filter/update_delay.html.twig'
        bulk_action:
            export: 'admin/grid/bulk_action/export.html.twig'
    grids:
        sylius_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.brand.class%"
                    repository:
                        method: createAdminGridQueryBuilder
            sorting:
                createdAt: desc
            fields:
                id: 
                    type: string
                code:
                    type: string
                name:
                    type: string
                createdAt:
                    type: datetime
                    sortable: ~
                updatedAt:
                    type: datetime
                    sortable: ~
                enabled:
                    type: twig
                    options:
                        template: "@SyliusAdmin/shared/grid/field/boolean.html.twig"
                associated_products:
                    path: .
                    type: twig
                    options:
                        template: "admin/grid/field/associated_products.html.twig"
                associated_products_alt:
                    type: associated_products
                    label: sylius.ui.associated_products
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete
                    show_products:
                        type: show_products
                        label: sylius.ui.show_products
                        options:
                            link:
                                route: sylius_shop_branded_products_index
                                parameters:
                                    code: resource.code
                    show_products_alt:
                        type: default
                        icon: "tabler:eye"
                        options:
                            link:
                                route: sylius_shop_branded_products_index
                                parameters:
                                    code: resource.code
                bulk:
                    delete:
                        type: delete
                    export:
                        type: export
            filters:
                search:
                    type: string
                    options:
                        fields: [code, name]
                enabled:
                    type: boolean
                createdAt:
                    type: date
                    options:
                        field: createdAt
                        inclusive_to: true
                update_delay:
                    type: update_delay
        
        sylius_admin_product:
            filters:
                brand:
                    type: entity
                    form_options:
                        class: "%sylius.model.brand.class%"
                        choice_label: name
            fields:
                mainTaxon:
                    enabled: false
                image:
                    position: 1
                enabled:
                    position: 2
