sylius_grid:
    templates:
        action:
            show_products: 'admin/grid/action/show_products.html.twig'
        filter:
            update_delay: 'admin/grid/filter/update_delay.html.twig'
        bulk_action:
            export: 'admin/grid/bulk_action/export.html.twig'
