sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: '/%sylius_admin.path_name%'

sylius_admin_brand_create_from_code:
    path: '/%sylius_admin.path_name%/brands/{code}/new'
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.brand::createAction
        _sylius:
            section: admin
            template:
                '@SyliusAdmin\shared\crud\create.html.twig'
            factory:
                method: createFromCodeWithName
                arguments:
                    - $code

sylius_admin_brand_bulk_export:
    path: '/%sylius_admin.path_name%/brands/export'
    methods: [POST]
    defaults:
        _controller: sylius.controller.brand::bulkExportAction
        _sylius:
            section: admin
            paginate: false
            repository:
                method: findByIds
                arguments: [$ids]
    
sylius_admin_brand:
    resource: |
        alias: sylius.brand
        section: admin
        templates: '@SyliusAdmin\\shared\\crud'
        redirect: update
        form:
            type: App\Form\Type\BrandType
        grid: sylius_admin_brand
    type: sylius.resource
    prefix: '/%sylius_admin.path_name%'

sylius_admin_brand_apply_state_machine_transition:
    path: '/%sylius_admin.path_name%/brands/{id}/{transition}'
    methods: [PUT]
    defaults:
        _controller: sylius.controller.brand::applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: sylius_brand
                transition: $transition
            redirect: referer

sylius_admin_shipment_prepare:
    path: '/%sylius_admin.path_name%/orders/{orderId}/shipment/{shipmentId}/prepare'
    methods: [PUT]
    defaults:
        _controller: sylius.controller.shipment::applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: sylius_shipment
                transition: prepare
            redirect: referer
            repository:
                method: findOneByOrderId
                arguments:
                    - $shipmentId
                    - $orderId
