sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: '/%sylius_admin.path_name%'

sylius_admin_brand_create_from_code:
    path: '/%sylius_admin.path_name%/brands/{code}/new'
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.brand::createAction
        _sylius:
            section: admin
            template:
                '@SyliusAdmin\shared\crud\create.html.twig'
            factory:
                method: createFromCodeWithName
                arguments:
                    - $code

sylius_admin_brand:
    resource: |
        alias: sylius.brand
        section: admin
        templates: '@SyliusAdmin\\shared\\crud'
        redirect: update
        form:
            type: App\Form\Type\BrandType
        grid: sylius_admin_brand
    type: sylius.resource
    prefix: '/%sylius_admin.path_name%'
